# Generated by Django 4.1.7 on 2023-02-26 16:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=300)),
                ('name', models.CharField(max_length=25)),
                ('main_image', models.ImageField(default='', help_text='add main about img 1280x853', upload_to='about/')),
                ('text', ckeditor.fields.RichTextField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons/')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(default='', max_length=100)),
                ('font_awesome_icon', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, default='', null=True, upload_to='icons/social/')),
                ('font_awesome_code', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
        ),
    ]
