# Generated by Django 4.1.7 on 2023-02-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactlink_font_awesome_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlink',
            name='icon_dark',
            field=models.FileField(blank=True, null=True, upload_to='icons/contacts/'),
        ),
    ]
