# Generated by Django 4.1.7 on 2023-02-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactlink_icon_dark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlink',
            name='icon_dark',
        ),
        migrations.AddField(
            model_name='social',
            name='icon_dark',
            field=models.FileField(blank=True, default='', null=True, upload_to='icons/social/'),
        ),
    ]
