# Generated by Django 4.1.7 on 2023-02-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contactlink_icon_dark_social_icon_dark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.ImageField(blank=True, default='', null=True, upload_to='icons/social/'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon_dark',
            field=models.ImageField(blank=True, default='', null=True, upload_to='icons/social/'),
        ),
    ]
