# Generated by Django 4.1.7 on 2023-02-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_image_name_videoyoutube_audiointernal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyoutube',
            name='video_frame',
            field=models.TextField(max_length=900),
        ),
    ]
