# Generated by Django 4.1.7 on 2023-02-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_videoyoutube_video_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoyoutube',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube', to='blog.post'),
        ),
    ]
