# Generated by Django 4.1.7 on 2023-02-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_videoyoutube_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiointernal',
            name='site_play',
            field=models.BooleanField(default=False),
        ),
    ]
