# Generated by Django 4.1.7 on 2023-05-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_audiointernal_tracknumber_alter_audiointernal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiointernal',
            name='name',
            field=models.CharField(default='Unknown', max_length=250, verbose_name='Название песни'),
        ),
    ]
