# Generated by Django 4.1.7 on 2023-05-08 16:12

import autoslug.fields
import blog.models
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_audiointernal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiointernal',
            name='track',
            field=models.FileField(upload_to=blog.models.upload_directory, validators=[blog.validators.validate_file_extension], verbose_name='Аудио файл'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=blog.models.upload_directory, validators=[blog.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Вступительный текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
