# Generated by Django 4.1.7 on 2023-05-19 10:49

import blog.models
import blog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to=blog.models.upload_directory, validators=[blog.validators.validate_file_extension], verbose_name='Альбом целиком')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
