# Generated by Django 4.1.7 on 2023-05-19 11:01

import blog.models
import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_uploadfile_annotations_alter_uploadfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на скачивание'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.upload_directory, validators=[blog.validators.validate_file_extension], verbose_name='Альбом целиком'),
        ),
    ]
